name: Python CI with Artifact Upload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Firefox
      run: sudo apt-get install -y firefox
      
    - name: Open YouTube in Firefox
      run: |
        osascript -e 'tell application "Firefox" to open location "https://www.youtube.com/watch?v=4ktJ1Xbudpc"'

    - name: Wait for 5 seconds
      run: |
        sleep 5

    - name: Close Firefox
      run: |
        osascript -e 'quit app "Firefox"'


    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytube
        pip install wython
        pip install yt-dlp

    - name: Run Python script
      run: |
        yt-dlp --cookies-from-browser firefox https://www.youtube.com/watch?v=4ktJ1Xbudpc
        python -u b.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: ./a.mp4
