name: WebTorrent Magnet Downloader

on:
  push:
    paths:
      - magnet_list.txt

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ✅ 1. 写入 package.json，声明这是一个 ES module 项目
      - name: Write package.json
        run: |
          echo '{
            "type": "module"
          }' > package.json


      # ✅ 2. 安装依赖：webtorrent（基于 ESM）
      - name: Install webtorrent
        run: npm install webtorrent

      # ✅ 3. 运行下载脚本（download_magnets.js 必须使用 import）
      - name: Run magnet download script
        run: node download_magnets.js

      - name: Zip downloaded files
        run: zip -r downloaded.zip downloads/

      - name: Upload downloaded zip
        uses: actions/upload-artifact@v4
        with:
          name: downloaded-zip
          path: downloaded.zip

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: download-log
          path: output.txt
