name: Python Connect to MongoDB (Manual Docker)



jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo

      - name: Start MongoDB manually
        run: |
          docker run -d --name mongodb -p 27017:27017 mongo:6.0 --bind_ip_all

      - name: Wait for MongoDB to be ready
        run: |
          sleep 20
          docker logs mongodb

      - name: Run Python script to connect MongoDB
        run: python connect_mongo.py
