name: This_workflow_never_end

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  run-python:
    runs-on: ubuntu-latest
    timeout-minutes: 355  # 5 小时 55 分钟

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'


      - name: Run long Python script
        run: python long_script.py || echo "Python script exited with error"

      - name: Start new workflow if timeout is near
        if: always()
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/This_workflow_never_end.yaml/dispatches \
          -d '{"ref":"main"}'
